[blockchain]
chain_id = "31337"
chain_name = "hardhat"

["blockchain.wallet.default"]
private_key = "8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba"

[lit]
env = "dev"

[ipfs]
gateway = "https://cloudflare-ipfs.com/ipfs/"

[node.http]
port = "7475"

[node]
domain = "127.0.0.1"
admin_address = "e7f1725e7734ce288f8367e1bb143e90bb3f0512"
coms_keys_receiver_privkey = "0xfb3a6bb884584f8c1d76b2f1d38d5236a29a3d6c8f2a18ba625d46ad28bc61d3"
coms_keys_sender_privkey = "0xbfac351223a087cd679f4ec1f5f77bc949c57b9bf8e76a03bc9879990b4edeff"
enable_actions_allowlist = "false"
enable_epoch_transitions = "true"
enable_rate_limiting = "false"
enable_ecdsa_dkg = "true"
public_key = "0337b84de6947b243626cc8b977bb1f1632610614842468dfa8f35dcbbc55a515e"
rpc_url = "http://localhost:8545"
staker_address = "0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc"

[subnet]
id = "fA80600109BA720f7d8C4EAD46537726a0216aAf"
