[blockchain]
chain_id = "31337"
chain_name = "hardhat"

["blockchain.wallet.default"]
private_key = "47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a"

[lit]
env = "dev"

[ipfs]
gateway = "https://cloudflare-ipfs.com/ipfs/"

[node.http]
port = "7474"

[node]
domain = "127.0.0.1"
admin_address = "e7f1725e7734ce288f8367e1bb143e90bb3f0512"
coms_keys_receiver_privkey = "0xfb3a6bb884584f8c1d76b2f1d38d5236a29a3d6c8f2a18ba625d46ad28bc61d3"
coms_keys_sender_privkey = "0xbfac351223a087cd679f4ec1f5f77bc949c57b9bf8e76a03bc9879990b4edeff"
enable_actions_allowlist = "false"
enable_epoch_transitions = "true"
enable_rate_limiting = "false"
enable_ecdsa_dkg = "true"
public_key = "03bf6ee64a8d2fdc551ec8bb9ef862ef6b4bcb1805cdc520c3aa5866c0575fd3b5"
rpc_url = "http://localhost:8545"
staker_address = "0x15d34aaf54267db7d7c367839aaf71a00a2c6a65"

[subnet]
id = "fA80600109BA720f7d8C4EAD46537726a0216aAf"
